# Generated by Django 2.1.5 on 2019-02-08 20:41

from django.db import migrations, models
import regulations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activation', models.DateTimeField(blank=True)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, upload_to=regulations.models.only_filename)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('prev_version', models.CharField(blank=True, max_length=100)),
                ('organisation', models.CharField(blank=True, max_length=150)),
                ('regulation_organization_link', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
