# Generated by Django 2.1.5 on 2019-02-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certf_number', models.IntegerField()),
                ('first_name_en', models.CharField(max_length=140)),
                ('last_name_en', models.CharField(max_length=140)),
                ('last_name_ukr', models.CharField(max_length=140)),
                ('first_name_ukr', models.CharField(max_length=140)),
                ('second_name_ukr', models.CharField(max_length=140)),
                ('born', models.DateField()),
                ('inn', models.PositiveIntegerField()),
                ('date_of_issue', models.DateField()),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('valid_type', models.IntegerField(choices=[(0, 'Бессрочный'), (1, 'Срочный')], default=0)),
                ('form_number', models.CharField(blank=True, max_length=40, null=True)),
                ('study_start', models.DateField()),
                ('study_finish', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Выдан'), (2, 'Аннулирован')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_en', models.CharField(blank=True, max_length=140)),
                ('last_name_en', models.CharField(blank=True, max_length=140)),
                ('last_name_ukr', models.CharField(max_length=140)),
                ('first_name_ukr', models.CharField(max_length=140)),
                ('second_name_ukr', models.CharField(blank=True, max_length=140)),
                ('born', models.DateField()),
                ('died', models.DateField(blank=True, null=True)),
                ('inn', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'ordering': ('last_name_ukr', 'first_name_ukr'),
            },
        ),
        migrations.CreateModel(
            name='TrainigDirections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_title', models.CharField(max_length=140)),
                ('level', models.IntegerField(choices=[(0, '---'), (1, 'Отримання'), (2, 'Підтвердження')], default=0)),
                ('allow_functions', models.IntegerField(choices=[(0, '---'), (1, 'Управлiння'), (2, 'Эксплуатацiя')], default=0)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificated', to='mariner.Sailor'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mariner.TrainigDirections'),
        ),
    ]
