# Generated by Django 2.1.5 on 2019-02-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0002_auto_20190211_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainigdirections',
            name='direction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
