# Generated by Django 2.1.5 on 2019-02-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0003_trainigdirections_direction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainigdirections',
            name='allow_functions',
            field=models.CharField(choices=[('', '---'), ('Управлiння', 'Управлiння'), ('Експлуатація', 'Експлуатація')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainigdirections',
            name='direction_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trainigdirections',
            name='level',
            field=models.CharField(choices=[('', '---'), ('Отримання', 'Отримання'), ('Підтвердження', 'Підтвердження')], default='', max_length=20),
        ),
    ]
