# Generated by Django 2.1.5 on 2019-02-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0004_auto_20190213_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='SailorManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrainigOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(blank=True, max_length=140)),
                ('orgnisation_email', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='person',
            new_name='sailor',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Обробка'), (2, 'Прісвоення'), (3, 'Выдан'), (4, 'Аннулирован')], default=0),
        ),
        migrations.AlterField(
            model_name='trainigdirections',
            name='allow_functions',
            field=models.CharField(choices=[('---', '---'), ('Управлiння', 'Управлiння'), ('Експлуатація', 'Експлуатація')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainigdirections',
            name='level',
            field=models.CharField(choices=[('---', '---'), ('Отримання', 'Отримання'), ('Підтвердження', 'Підтвердження')], default='', max_length=20),
        ),
    ]
