# Generated by Django 2.1.5 on 2019-02-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0005_auto_20190222_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='trainigOrganisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained', to='mariner.TrainigOrganisation'),
        ),
    ]
