# Generated by Django 2.1.5 on 2019-02-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0006_certificate_trainigorganisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SailorManager',
        ),
        migrations.AddField(
            model_name='trainigorganisation',
            name='directions',
            field=models.ManyToManyField(blank=True, to='mariner.TrainigDirections'),
        ),
    ]
