# Generated by Django 2.1.5 on 2019-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0007_auto_20190223_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='study_finish',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='study_start',
        ),
        migrations.AddField(
            model_name='sailor',
            name='sailor_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainigorganisation',
            name='activated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainigorganisation',
            name='active_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='inn',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='second_name_ukr',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(choices=[('Чернетка', 'Чернетка'), ('Обробка', 'Обробка'), ('Присвоення', 'Присвоення'), ('Видан', 'Видан'), ('Анульований', 'Анульований')], default='Чернетка'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='valid_type',
            field=models.IntegerField(choices=[('Безстроковий', 'Безстроковий'), ('Терміновий', 'Терміновий')], default='Безстроковий'),
        ),
        migrations.AlterField(
            model_name='sailor',
            name='inn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainigdirections',
            name='allow_functions',
            field=models.CharField(choices=[('---', '---'), ('Управлiння', 'Управлiння'), ('Експлуатація', 'Експлуатація')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainigdirections',
            name='level',
            field=models.CharField(choices=[('---', '---'), ('Отримання', 'Отримання'), ('Підтвердження', 'Підтвердження')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainigorganisation',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='directioned', to='mariner.TrainigDirections'),
        ),
    ]
