# Generated by Django 2.1.5 on 2019-03-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0008_auto_20190307_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certf_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainigdirections',
            name='price_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainigdirections',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
