# Generated by Django 2.1.5 on 2019-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0009_auto_20190307_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='direction_allow_functions',
            field=models.CharField(choices=[('---', '---'), ('Управлiння', 'Управлiння'), ('Експлуатація', 'Експлуатація')], default='---', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='direction_level',
            field=models.CharField(choices=[('---', '---'), ('Отримання', 'Отримання'), ('Підтвердження', 'Підтвердження')], default='---', max_length=20),
        ),
    ]
