# Generated by Django 2.1.5 on 2019-03-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0010_auto_20190307_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certf_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='direction_level',
            field=models.CharField(choices=[('---', '---'), ('Отримання', 'Отримання'), ('Підтвердження', 'Підтвердження')], default='Отримання', max_length=20),
        ),
    ]
