# Generated by Django 2.1.5 on 2019-03-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0011_auto_20190307_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainigorganisation',
            name='organisation_id',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
