# Generated by Django 2.1.5 on 2019-03-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0012_trainigorganisation_organisation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(choices=[('Чернетка', 'Чернетка'), ('Обробка', 'Обробка'), ('Присвоення', 'Присвоення'), ('Видан', 'Видан'), ('Анульований', 'Анульований')], default='Чернетка', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='valid_type',
            field=models.IntegerField(choices=[('Безстроковий', 'Безстроковий'), ('Терміновий', 'Терміновий')], default='Безстроковий', max_length=20),
        ),
    ]
