# Generated by Django 2.1.5 on 2019-03-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0014_auto_20190313_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Обробка'), (1, 'Видан'), (2, 'Анульрований')], default=0, null=True),
        ),
    ]
