# Generated by Django 2.1.5 on 2019-03-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0015_auto_20190314_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Чернетка'), (1, 'Обробка'), (2, 'Видан'), (3, 'Анульрований')], default=0, null=True),
        ),
    ]
