# Generated by Django 2.1.5 on 2019-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0016_auto_20190314_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='inn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Чернетка'), (1, 'Обробка'), (2, 'Видан'), (3, 'Анульований')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='valid_type',
            field=models.IntegerField(choices=[(0, 'Безстроковий'), (1, 'Терміновий')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sailor',
            name='inn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
