# Generated by Django 2.1.5 on 2019-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0017_auto_20190314_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ntz_status',
            field=models.IntegerField(choices=[(0, 'Чернетка'), (1, 'Обробка')], default=0, null=True),
        ),
    ]
