# Generated by Django 2.1.5 on 2019-03-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0018_certificate_ntz_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='ntz_status',
        ),
    ]
