# Generated by Django 2.1.5 on 2019-03-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0019_remove_certificate_ntz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ntz_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
