# Generated by Django 2.1.5 on 2019-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0020_certificate_ntz_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainigdirections',
            name='organizationName',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
