# Generated by Django 2.1.5 on 2019-03-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0021_trainigdirections_organizationname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainigdirections',
            name='organizationName',
        ),
    ]
