# Generated by Django 2.1.5 on 2019-03-27 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0022_remove_trainigdirections_organizationname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailor',
            name='sailor_id',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='training_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed', to='mariner.TrainigDirections'),
        ),
    ]
