# Generated by Django 2.1.5 on 2019-03-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariner', '0023_auto_20190327_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certf_id',
        ),
        migrations.RemoveField(
            model_name='trainigdirections',
            name='direction_id',
        ),
    ]
